# Generated by Django 4.1.7 on 2023-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
